# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a0f10eb0f25b7d88113f10e8141121f3e8e1e2d9815d94ab75edbcb05cef4070cb93cfa40b971d21a832012f483fdd283882263fc05573f89dfbcb048c5e5b

test:
  secret_key_base: ea428c7e3b51fa32f2ec75b55c28116e7718426c85b56a208acfb182ca5960d73e816c0ee73e99013d3bbcbe9eb6cb23fc3a74eef79150ed274dbded23d013a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
